sudo: false
language: node_js
node_js:
  - 'stable'
  - 'iojs'
  - v5
  - v4
  - v6
  - v7

script: 'npm run cover'

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage